apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: etcd
spec:
  serviceName: etcd-cluster-headless
  replicas: 3
  selector:
    matchLabels:
      app: etcd
  template:
    metadata:
      labels:
        app: etcd
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "2379"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: etcd
          image: quay.io/coreos/etcd:v3.5.11
          ports:
            - containerPort: 2379
            - containerPort: 2380
          command:
            - /usr/local/bin/etcd
            - --name=$(POD_NAME)
            - --data-dir=/etcd-data
            - --initial-advertise-peer-urls=http://$(POD_NAME).etcd-cluster-headless:2380
            - --listen-peer-urls=http://0.0.0.0:2380
            - --listen-client-urls=http://0.0.0.0:2379
            - --advertise-client-urls=http://$(POD_NAME).etcd-cluster-headless:2379
            - --initial-cluster=etcd-0=http://etcd-0.etcd-cluster-headless:2380,etcd-1=http://etcd-1.etcd-cluster-headless:2380,etcd-2=http://etcd-2.etcd-cluster-headless:2380
            - --initial-cluster-state=new
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          volumeMounts:
            - mountPath: /etcd-data
              name: etcd-data
      terminationGracePeriodSeconds: 10
  volumeClaimTemplates:
    - metadata:
        name: etcd-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
