apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: ping
  template:
    metadata:
      labels:
        app: ping
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "5000"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: ping
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 5000
