name: CI/CD - Ping service - Build and Deploy

on:
  push:
    branches:
      - dev
    paths:
      - '!README.md'
  pull_request:
    branches:
      - main

env:
  AKS_RESOURCE_GROUP: rg-marko-aks-weu-01
  AKS_CLUSTER_NAME: aks-ls-dev-euwe-01
  ACR_REGISTRY: acrls.azurecr.io
  IMAGE_NAME: ping-service
  IMAGE_TAG: latest

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set AKS credentials
      run: |
        az aks get-credentials \
          --resource-group ${{ env.AKS_RESOURCE_GROUP }} \
          --name ${{ env.AKS_CLUSTER_NAME }} \
          --overwrite-existing

    - name: Log in to Azure Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.ACR_REGISTRY }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: ./ping-service
        file: ./ping-service/Dockerfile
        push: true
        platforms: linux/arm64
        tags: ${{ env.ACR_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

    - name: Install Helm
      uses: azure/setup-helm@v3
      with:
        version: v3.14.0

    - name: Deploy with Helm
      run: |
        helm upgrade --install ping ./ping-service --namespace default
        kubectl get pods -l app=ping

 